addCssClass(selector = "a[data-value='landing']", class = "activeLink")
addCssClass(selector = "a[data-value='dashboard']", class = "activeLink")
addCssClass(selector = "a[data-value='manual']", class = "activeLink")
shinyjs::disable(selector = "a[data-value='data']")
addCssClass(selector = "a[data-value='data']", class = "inactiveLink")
shinyjs::disable(selector = "a[data-value='qaqc']")
addCssClass(selector = "a[data-value='qaqc']", class = "inactiveLink")
shinyjs::disable(selector = "a[data-value='summaries']")
addCssClass(selector = "a[data-value='summaries']", class = "inactiveLink")
shinyjs::disable("runProcessCode")
shinyjs::disable("runIndicesCode")
shinyjs::disable("runQAQCCode")
shinyjs::disable("runSummariesCode")

## shinyjs::disable("runBootstrappCode")
## shinyjs::disable("runSummariesCode")

## shinyjs::disable("runEDACode")
## shinyjs::disable(selector = "a[data-value='eda']")
## addCssClass(selector = "a[data-value='eda']", class = "inactiveLink")
## shinyjs::disable("runAnalysisCode")
## shinyjs::disable(selector = "a[data-value='analysis']")
## addCssClass(selector = "a[data-value='analysis']", class = "activeLink")
