settings_box <-
  fluidRow(
    box(
      width = 6,
      title = "Path settings",
      solidHeader = TRUE,
      status = "success",
      textInput("settings_project_path_input",
        label = tags$span(
          "Project path: ",
          popify(icon("info-circle"),
            title = "Project path",
            content = "This is the path to the project. It is being displayed here incase you need to know where all these files are stored.  <b>There is no need to alter this location</b>")
        ),
        width = "400px"
      ),
      ## Input data path input
      textInput("settings_input_dir_input",
        label = tags$span(
          "Data input dir: ",
          popify(icon("info-circle"),
            title = "Input data directory",
            content = "This is the path in which this app will search for input files. <b>You are welcome to change this to another location if you wish</b>."
          )
        ),
        width = "400px"),
      ## files located in the above path
      ## verbatimTextOutput("settings_input_dir_files",placeholder = TRUE),
      div(
        style = "margin-bottom: 20px;", # Add 20px of space below the table
        reactableOutput("settings_input_dir_files") # Table for displaying filenames
      ),
      ## Data path input
      textInput("settings_data_dir_input",
        label = tags$span(
          "Data dir: ",
          popify(icon("info-circle"),
            title = "Data directory",
            content = "This is the path that this app will place intermediate data artifacts. <b>Typically, you should not need to alter this path.  However, if you have a need for any of the intermediate artifacts, you know where to find them.</b>."
          )
        ),
        width = "400px"),
      ## Params path input
      textInput("settings_params_dir_input",
        label = tags$span(
          "Parameters dir: ",
          popify(icon("info-circle"),
            title = "Parameters directory",
            content = "This is the path that this app will look to acquire any data that might be considered non-data inputs - such as settings, lookups etc."
          )
        ),
        width = "400px"),
      ## Output path input
      textInput("settings_output_dir_input",
        label = tags$span(
          "Output dir: ",
          popify(icon("info-circle"),
            title = "Output directory",
            content = "This is the path that this app will place individual figures and tables."
          )
        ),
        width = "400px"),
      ## Documents path input
      textInput("settings_docs_dir_input",
        label = tags$span(
          "Documents dir: ",
          popify(icon("info-circle"),
            title = "Documents directory",
            content = "This is the path that this app will place any document outputs (including reports)."
          )
        ),
        width = "400px")
    ),
    box(
      title = "Temporary files",
      width = 6,
      solidHeader = TRUE,
      status = "success",
      ## Status path input
      textInput("settings_status_path_input",
        label = tags$span(
          "Temporary path: ",
          popify(icon("info-circle"),
            title = "Temporary path",
            content = "This is the path to the temporary directory used internally by the app to store files.  It is being displayed here incase you need to know where all these files are stored.  <b>there is no need to alter this location</b>"
          )
        ),
        width = "400px"
      ),
      ## Status file input
      textInput("settings_status_file_input",
        label = tags$span(
          "Status filename: ",
          popify(icon("info-circle"),
            title = "Status file",
            content = "This is the name of file that stores the status information for this project.  It is being displayed here incase you need to know where all these files are stored.  <b>there is no need to alter this file name</b>"
          )
        ),
        width = "400px"),
      ## Log file input
      textInput("settings_log_file_input",
        label = tags$span(
          "Log filename: ",
          popify(icon("info-circle"),
            title = "Logfile",
            content = "This is the name of the log file that stores the logs for this project.  It is being displayed here incase you need to know where all these files are stored.  <b>there is no need to alter this file name</b>"
          )
        ),
        width = "400px")
    ),
    ## Run stages
    box(
      title = "Run settings",
      width = 6,
      solidHeader = TRUE,
      status = "success",
      actionButton("runClearPreviousDataCode",
        label = tags$span(" Clear previous data", popify(icon("info-circle"), title = "Clear data",
          content = "Click this button to clear all data generated by this application.  <b>This will not delete the input data</b>.  The purpose is to ensure that artifacts (data) generated during previous runs of this analysis do not inadvertently impact on the current run.")),
        icon = icon("play"), class = "btn-default", style = "width: auto !important;"),
      ## Run stages input
      textInput("settings_run_stages_input",
        label = tags$span(
          "Run stages: ",
          popify(icon("info-circle"),
            title = "Run stages",
            content = "This indicates which stages of the analyses you wish to run.  You should provide a comma separated set of numbers.  For example, to run stages 1 through to 3, you would enter 1,2,3.  Note, run stage 1 is just setting things up."
          )
        ),
        width = "400px"),
      div(
        tags$span(
               "Run in sequence: ",
               popify(icon("info-circle"),
                      title = "Run in sequence",
                      content = "This indicates whether you wish to run the stages in sequence or not.  If you select Yes, then the Run buttons and side tab menus will only become active after the proceding stage has successfully completed.  If you select No, then all Run buttons and side tab menus will always be active and you are free to run stages out of sequence (however this is only recommended when you know that the stages have all ready been run and you are simply wishing to review all outputs in a returning session."
                      ),
               switchInput(inputId = "settings_run_in_sequence", value = TRUE, onLabel = "Yes", offLabel = "No"),
               ),
        ),
      ## radioButtons(
      ##   "lor_input",
      ##   label = tags$span(
      ##     "Limit of reporting (LoR):",
      ##     popify(icon("info-circle"),
      ##       title = "Limit of Reporting",
      ##       content = "Traditionally, values that represent Limit of Reporting (LoR) were replaced with half the LoR value.  For example, a value of <0.02 would be replaced with 0.01.  However, modern statistical analyses have more appropriate ways of incorporating LoR information.  Rather than arbitrarily replace values with half the LoR, we retain thier value and flag them as censored and allow the statistical properties of disbutions to handle them more naturally."
      ##     )
      ##   ),
      ##   choices = c(
      ##     "Censor at value (e.g. <0.02 ---> 0.02)" = "1",
      ##     "Divide by 2 (e.g. <0.02 ---> 0.01)" = "2"
      ##   )#,
      ##   #selected = status_$settings$lor$item
      ## )
    ),
    box(
      title = span(icon("info", style = "margin-right: 10px;"), "Settings Instructions"),
      width = 12,
      solidHeader = TRUE,
      status = "info",
      ## HTML(markdown::mark(text = "This is some **text**")),
      htmltools::includeMarkdown("../md/settings.md")
    )
  )

landing_tab <- tabItem(
  tabName = "landing",
  fluidRow(
    h2("Darwin Harbour Water Quality Monitoring Analysis Platform", style = "margin-left: 15px;"),
    box(
      title = "Settings",
      width = 6,
      solidHeader = TRUE,
      status = "primary",
      p("The following settings are indicate the location and names of directories and files used for input and output by this application.  Initially, the values displayed are the defaults."),
      settings_box
    ),
    box(
      title = span(icon("info", style = "margin-right: 10px;"), "General Instructions"),
      width = 6,
      solidHeader = TRUE,
      status = "info",
      tabsetPanel(
        id = "instructions_tabs",
        tabPanel(
          title = "General instructions",
          box(
            title = span(icon("info", style = "margin-right: 10px;"), "General Instructions"),
            width = 12,
            solidHeader = TRUE,
            status = "info",
            ## HTML(markdown::mark(text = "This is some **text**")),
            htmltools::includeMarkdown("../md/instructions.md")
          )
        ),
        tabPanel(
          title = "Data requirements",
          box(
            title = span(icon("info", style = "margin-right: 10px;"), "Data requirements"),
            width = 12,
            collapsible = TRUE,
            solidHeader = TRUE,
            status = "info",
            htmltools::includeMarkdown("../md/raw_data.md")
          ),
          )
      )
    ),
    )
)

